@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/Global-Rainbow-Map/project>
	deps:runtime-requirement         [ deps:on "XML::LibXML 1.70"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "Color::Library"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.61"^^deps:CpanId ].

